#!/bin/sh

set -e

lb config noauto \
    --mode debian \
    --apt aptitude \
    --aptitude-options --assume-yes \
    --architectures amd64 \
    --archive-areas "main contrib non-free" \
    -d buster \
    --system live \
    --backports true \
    --bootappend-live "boot=live noautologin nocomponents=user-setup,gdm3,kdm,lightdm,lxdm,nodm,slim,xinit,kaboom,xserver-xorg,xfce4-panel quite splash" \
    --binary-images iso \
    --bootloaders grub-efi \
    --memtest none \
    --debconf-frontend noninteractive \
    --debian-installer false \
    --debian-installer-gui false \
    --image-name "maxeff-live" \
    --iso-application "maxeff" \
    --iso-preparer "0.5" \
    --iso-publisher "Deny" \
    --mirror-bootstrap http://deb.debian.org/debian/ \
    --mirror-binary http://deb.debian.org/debian/ \
    "${@}"